### ISSUE TITLE
Wiz queries return decoding error: "invalid character '<'"

### ISSUE THREAD

**Issue by bretlowery** [turbot/steampipe-plugin-wiz#12]
**Describe the bug**
Wiz queries return:
Error: decoding response: invalid character '<' looking for beginning of value (SQLSTATE HV000)

**Steampipe version (`steampipe -v`)**
Steampipe v0.21.1

**To reproduce**
1. Install steampipe
2. Add Wiz plugin (Latest v downloaded 10/16/2023)
3. Configure Wiz credentials for Steampipe
4. Run any query
```
> select
  id,
  status,
  severity,
  created_at
from
  wiz_issue
where
  severity = 'CRITICAL';
  
Error: decoding response: invalid character '<' looking for beginning of value (SQLSTATE HV000)
```

**Expected behavior**
Results are returned

**Additional context**
Brand-new Steampipe install; verified Wiz credentials via Postman

**Comment by misraved** [comment]
Welcome to Steampipe @bretlowery and thank you so much for creating the issue with such great details.

The API does return a very weird message, do we only get it if we specify the wrong two-digit values in the XX in https://api.usxx.app.wiz.io/graphql)? Are there more scenarios where we are likely to get into this error?

**Comment by bretlowery** [comment]
If it’s failing in the angle bracket, quite possibly, but not sure of specifics.

**Comment by misraved** [comment]
Apologies for the radio silence on this issue @bretlowery !!

As you mentioned, the error is returned by the Wiz API without any clear instructions on what failed. When I tamper the `url` config argument,  I get the following error - 

```
select
  id,
  status,
  severity,
  created_at
from
  wiz_issue
where
  severity = 'CRITICAL';

Error: wiz: failed to parse token response: invalid character 'U' looking for begining of value (SQLSTATE HV000)

+----+--------+----------+------------+
| id | status | severity | created_at |
+----+--------+----------+------------+
+----+--------+----------+------------+
```
