### ISSUE TITLE
We see STerr in the CSV results, it should be an error (in the stderr)

### ISSUE THREAD

**Issue by Dor-Swisa** [turbot/steampipe-plugin-wiz#42]
**Describe the bug**
We see STerr in the CSV results, it should be an error (in the stderr)

**Steampipe version (`steampipe -v`)**
Example: v0.21.2

**Plugin version (`steampipe plugin list`)**
Example: v0.3.0

**To reproduce**
Run the plugin with the wrong credentials and see that the errors are written in the stdout 
 
**Expected behavior**
The error will be written in the stderr

**Additional context**

**Comment by ParthaI** [comment]
Hello @Dor-Swisa, I’m sorry to hear you're encountering this issue. Could you please try running the queries again after updating the Steampipe CLI to the latest version? Let us know if the error still persists. Thanks!

**Comment by ParthaI** [comment]
Hi @Dor-Swisa, yes, please try running the query after installing the Steampipe CLI. I'd like to confirm whether the issue is related to the plugin build or the Steampipe CLI itself, as errors can sometimes occur due to a faulty build.

**Comment by pskrbasu** [comment]
> I want to use the plugin itself (Binary) without the CLI

Hey @Dor-Swisa, if you use the plugin without the Steampipe CLI, it is expected to get the errors you are seeing. The error handling and display code is present in the CLI itself.
Also, may I ask how you're using the plugin binary without the CLI?

If you are not looking to use Steampipe CLI and are only interested in getting the CSV results, you can also try out our standalone [Export tool](https://steampipe.io/docs/steampipe_export/overview).
Here is the [wiz plugin export tool](https://hub.steampipe.io/plugins/turbot/wiz#steampipe-export).
