### ISSUE TITLE
wiz_user limit

### ISSUE THREAD

**Issue by nogarab** [turbot/steampipe-plugin-wiz#46]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.17.4

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**
](https://github.com/turbot/steampipe-plugin-wiz/issues)

**Comment by misraved** [comment]
@nogarab apologies for the delayed response!!

Could you please share what issue you are running into?

**Comment by misraved** [comment]
Hello @nogarab ,

We haven’t received a response in a while, so we’re going to close this issue for now. If this is still a concern or if you have additional details to share, please don’t hesitate to reopen the issue, and we’ll be happy to assist you further.

Thank you for your understanding, and we appreciate your contributions!!
